"""Inject Open Graph + Twitter Card meta tags into every page so links
look rich when shared to WeChat / Twitter / Slack.

Material's `social` plugin can do this but needs cairosvg + image
rendering that silently no-ops in some CI environments. This hook is
simpler: it derives all tags from page + site config, no images.

og:image points at assets/og-card.png — a pre-generated 1200x630 card
checked into the repo (regenerate with scripts/gen_og_card.py when the
branding text changes). One default card for every page.
"""
import html


def on_post_page(output, page, config, **kwargs):
    meta = page.meta or {}
    title = meta.get("title") or page.title or config.get("site_name", "")
    desc = meta.get("description") or config.get("site_description", "")
    url = page.canonical_url or ""
    site = config.get("site_name", "")

    # Static share-card image, generated by scripts/gen_og_card.py and
    # checked in as assets/og-card.png (1200x630). One default card for all
    # pages — crawlers need an absolute URL and a raster format, so the SVG
    # logo won't do.
    image = ""
    site_url = (config.get("site_url") or "").rstrip("/")
    if site_url:
        image = f"{site_url}/assets/og-card.png"

    def add(attr, key, val):
        return f'<meta {attr}="{key}" content="{html.escape(str(val), quote=True)}">'

    tags = [
        add("property", "og:type", "website"),
        add("property", "og:site_name", site),
        add("property", "og:title", title),
        add("property", "og:description", desc),
        add("property", "og:url", url),
        add("property", "og:locale", "zh_CN"),
        add("property", "og:image", image),
        add("property", "og:image:width", "1200" if image else ""),
        add("property", "og:image:height", "630" if image else ""),
        add("name", "twitter:card", "summary_large_image" if image else "summary"),
        add("name", "twitter:title", title),
        add("name", "twitter:description", desc),
        add("name", "twitter:image", image),
    ]
    block = "\n".join(t for t in tags if 'content=""' not in t)
    return output.replace("</head>", block + "\n</head>", 1)
